@baseurl = http://localhost/api

###
# @name Login
POST {{baseurl}}/auth/token/login/
Content-Type: application/json

{
    "email": "a@a.local",
    "password":"admin"
}
###

@token = {{Login.response.body.auth_token}}

### Тест тэгов

# Список
GET {{baseurl}}/tags/
Authorization: token {{ token }}

###

# Экземпляр
GET {{baseurl}}/tags/2/
Authorization: token {{ token }}

### Тест ингредиентов

# Список
GET {{baseurl}}/ingredients/
Authorization: token {{token}}

###

# Экземпляр
GET {{baseurl}}/ingredients/3/
Authorization: token {{token}}

### Тест рецептов

# Список
GET {{baseurl}}/recipes/
Authorization: token {{token}}

###

GET {{baseurl}}/recipes/0/
Authorization: token {{token}}

