name: Foodgram test, rebuild and deploy

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r ./backend/requirements.txt
    
    - name: Test with flake8
      run: |
        python -m flake8 backend/
    
  build_and_push_to_docker_hub:
    if: github.ref == 'refs/heads/master'
    name: Builds image and push it to Docker hub
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push to Docker hub
      uses: docker/build-push-action@v3
      with:
        context: "./backend"
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

  deploy: 
    if: github.ref == 'refs/heads/master'
    name: Deploying docker container to remote server
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Prepare tar to migrate
      run: |
        mkdir ../app
        cp -TR ./data ../app/data
        cp -TR ./docs ../app/docs
        cp -TR ./infra ../app/infra
        cp -TR ./frontend ../app/frontend
        tar -cvf deploy.tar ../app/
    
    - name: Copytar file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "deploy.tar"
        target: "~/"

    - name: Execute remote ssh to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          tar -xvf deploy.tar
          cd ~/app/infra
          docker-compose stop
          docker-compose rm -f backend
          docker pull offlinexaa/foodgram_backend:latest
          docker-compose up -d
          docker-compose exec backend python manage.py makemigrations
          docker-compose exec backend python manage.py migrate
          docker-compose exec backend python manage.py collectstatic --no-input

  notify:
    name: Send notification in Telegram
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
